spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:finsight}?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: ${SHOW_SQL:false}
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      connect-timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

  cache:
    type: ${CACHE_TYPE:simple}
    jcache:
      config: classpath:ehcache.xml

hibernate:
  cache:
    enabled: ${CACHE_ENABLED:true}

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${ENCRYPT_KEY:defaultDevKey123}

news:
  marketaux:
    api:
      base-url: ${MARKETAUX_API_URL:https://api.marketaux.com/v1/news/all}
      api-key: ${MARKETAUX_API_KEY}

ai:
  openai:
    api:
      base-url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
      api-key: ${OPENAI_API_KEY}
      model: ${OPENAI_MODEL:gpt-3.5-turbo}
  djl:
    model:
      name: ${DJL_MODEL_NAME:cardiffnlp/twitter-roberta-base-sentiment-latest}
    engine: ${DJL_ENGINE:pytorch}
    device: ${DJL_DEVICE:cpu}
    performance:
      enable-caching: true
      cache-size: 500

redis:
  enabled: ${REDIS_ENABLED:true}
  connection-timeout: 2000
  command-timeout: 2000
  retry-attempts: 3
  retry-delay: 1000