spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=false&verifyServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      validation-timeout: 5000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 100
        jdbc:
          time_zone: UTC
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

  cache:
    type: redis
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
        shutdown-timeout: 100ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.sleekydz86.finsight: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.springframework.web: ${WEB_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 100MB
    max-history: 30

resilience4j:
  circuitbreaker:
    instances:
      newsScrapCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - java.lang.Exception
          - java.lang.RuntimeException
  retry:
    instances:
      newsScrapRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.lang.Exception
  timelimiter:
    instances:
      newsScrapTimeLimiter:
        timeout-duration: 30s

security:
  rate-limit:
    default-requests-per-minute: ${RATE_LIMIT_DEFAULT:60}
    admin-requests-per-minute: ${RATE_LIMIT_ADMIN:300}
    strict-requests-per-minute: ${RATE_LIMIT_STRICT:5}
  password:
    min-length: ${PASSWORD_MIN_LENGTH:16}
    require-special-chars: true
    require-numbers: true
    require-uppercase: true
    require-lowercase: true
  jwt:
    secret: ${JWT_SECRET}
    expiration-period: ${JWT_EXPIRATION:1800000}
    refresh-expiration-period: ${JWT_REFRESH_EXPIRATION:604800000}

cache:
  news:
    ttl: ${NEWS_CACHE_TTL:3600}
    max-size: ${NEWS_CACHE_MAX_SIZE:10000}