CREATE TABLE IF NOT EXISTS email_verifications (
    id BIGINT NOT NULL AUTO_INCREMENT,
    purpose VARCHAR(32) NOT NULL,
    purpose_label VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    challenge_id VARCHAR(36) NOT NULL,
    code_hash VARCHAR(100) NOT NULL,
    verified_code VARCHAR(6) NULL,
    last_entered_code VARCHAR(6) NULL,
    request_ip VARCHAR(64) NULL,
    request_location VARCHAR(255) NULL,
    requested_at DATETIME(6) NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    verified_at DATETIME(6) NULL,
    consumed_at DATETIME(6) NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_email_verifications_challenge (challenge_id),
    KEY idx_email_verifications_email_purpose (email, purpose, status),
    KEY idx_email_verifications_requested_at (requested_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
