spring:
  profiles:
    active: test
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
    job-repository:
      isolation-level-for-create: READ_COMMITTED
      table-prefix: BATCH_
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      initialization-fail-timeout: -1
      connection-init-sql: SET NAMES utf8mb4
      pool-name: BatchHikariPool
      register-mbeans: true
      allow-pool-suspension: false
      auto-commit: false
      read-only: false
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 100
        jdbc:
          time_zone: UTC
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        statistics:
          enabled: true
          generate_statistics: true
        session:
          events:
            log: false
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        statistics:
          enabled: true
          generate_statistics: true
        session:
          events:
            log: false

logging:
  level:
    com.sleekydz86.finsight: INFO
    org.springframework.batch: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.zaxxer.hikari: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/batch-application.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 3GB

batch:
  job:
    chunk-size: 100
    retry-limit: 3
    skip-limit: 10
    timeout: 300000
  database:
    cleanup-enabled: true
    cleanup-schedule: "0 0 2 * * ?"